const HOSTNAME = "https://tranquil-meadow-63605.herokuapp.com/"
const NUM_OF_ORDERS_EACH_PAGE = 10;
const NUM_OF_PRODUCTS_EACH_PAGE = 10000;
const NUM_OF_DISTRIBUTION_HISTORY_EACH_PAGE = 10;
export { HOSTNAME, NUM_OF_ORDERS_EACH_PAGE,
    NUM_OF_PRODUCTS_EACH_PAGE,
    NUM_OF_DISTRIBUTION_HISTORY_EACH_PAGE } 